### PR TITLE
Update videos

### PR DESCRIPTION
**Pull request by raer6**
Hello there!

I was wondering if this might be good addition to your list of videos.

Thank you for your consideration!

Radmila Ercegovac

### CODE REVIEW

**Comment by raer6** [comment]
I thought this video might be great add to you list of machine learning resources. It is giving close insights into what machine learning is in practice and is full of some great tips and exercises.

Thank you for your consideration.

**Comment by raer6** [comment]
Hi, I hope these titles might be a good match for your book and video lists.

Thank you for your consideration,

Rada.

**Comment by owainlewis** [comment]
Thanks @raer6 👍

**Comment by raer6** [comment]
Thanks a bunch!

Cheers,

Rada

**Pull request merged**
